# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b17e6aca0ab8e2d1906a8642fd6e82b19be19d90d3ceccd7b5e0c08a17a283b744c6429d12efa05ae9e050156793762f002a87aa85f360840f75049fe3b4506

test:
  secret_key_base: 0eb565415a62b0f7bbbad5e1250270df035dd2dd2412aac3142ed7ca465d28d56fb9162349ee66f2bc813bc2bbdcd3c49450dee5658891c3e9d0403f148496c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
